---
title: "string_practice"
author: "Adelaide Robinson"
date: '2022-08-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
alarm_report <- tribble(
         ~date,           ~building,                                              ~alarm_message,
  "2020-03-14", "Engineering-North", "10:02am – HVAC system down, facilities management alerted",
  "2020-03-15",         "Bren Hall",                    "8:24am – Elevator North out of service",
  "2020-04-10", "Engineering-South",     "12:41am – Fire alarm, UCSB fire responded and cleared",
  "2020-04-18",        "Engr-North",     "9:58pm – Campus point emergency siren, UCPD responded"
  )

```


```{r}
updated_alarm_report <- alarm_report |> 
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineer")) |>
  separate(col = building, into = c("building", "wing"), sep  = "-") |> 
  filter(str_detect(alarm_message, "responded")) |> 
  separate( col = alarm_message, into = c("message_time", "message"), sep = "–") |> 
  mutate(date = lubridate::ymd(date))
  
```

